// Sanitized Caldwell fixture — generated by scripts/sanitize-drummond.ts
// Source: budget-caldwell-2026-04-15.xlsx + cost code derived
// Generated: 2026-05-05
// Substitutions applied per .planning/fixtures/drummond/SUBSTITUTION-MAP.md (gitignored)
//
// DO NOT HAND-EDIT. Re-run `npx tsx scripts/sanitize-drummond.ts` to regenerate.

import type { CaldwellBudgetLine } from "./types";

export const CALDWELL_BUDGET_LINES: CaldwellBudgetLine[] = [
  {
    "id": "bl-caldwell-01101",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-01101",
    "original_estimate": 10000000,
    "revised_estimate": 10304348
  },
  {
    "id": "bl-caldwell-01104",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-01104",
    "original_estimate": 5000000,
    "revised_estimate": 5152174
  },
  {
    "id": "bl-caldwell-01201",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-01201",
    "original_estimate": 7500000,
    "revised_estimate": 7728261
  },
  {
    "id": "bl-caldwell-01301",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-01301",
    "original_estimate": 5000000,
    "revised_estimate": 5152174
  },
  {
    "id": "bl-caldwell-03110",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-03110",
    "original_estimate": 5000000,
    "revised_estimate": 5152174
  },
  {
    "id": "bl-caldwell-03112",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-03112",
    "original_estimate": 2500000,
    "revised_estimate": 2576087
  },
  {
    "id": "bl-caldwell-03115",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-03115",
    "original_estimate": 2500000,
    "revised_estimate": 2576087
  },
  {
    "id": "bl-caldwell-04101",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-04101",
    "original_estimate": 10000000,
    "revised_estimate": 10304348
  },
  {
    "id": "bl-caldwell-04201",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-04201",
    "original_estimate": 7500000,
    "revised_estimate": 7728261
  },
  {
    "id": "bl-caldwell-05101",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-05101",
    "original_estimate": 17500000,
    "revised_estimate": 18032609
  },
  {
    "id": "bl-caldwell-05201",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-05201",
    "original_estimate": 10000000,
    "revised_estimate": 10304348
  },
  {
    "id": "bl-caldwell-06101",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-06101",
    "original_estimate": 25000000,
    "revised_estimate": 25760870
  },
  {
    "id": "bl-caldwell-06201",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-06201",
    "original_estimate": 10000000,
    "revised_estimate": 10304348
  },
  {
    "id": "bl-caldwell-07101",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-07101",
    "original_estimate": 12500000,
    "revised_estimate": 12880435
  },
  {
    "id": "bl-caldwell-07201",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-07201",
    "original_estimate": 7500000,
    "revised_estimate": 7728261
  },
  {
    "id": "bl-caldwell-08101",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-08101",
    "original_estimate": 10000000,
    "revised_estimate": 10304348
  },
  {
    "id": "bl-caldwell-09101",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-09101",
    "original_estimate": 15000000,
    "revised_estimate": 15456522
  },
  {
    "id": "bl-caldwell-09201",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-09201",
    "original_estimate": 7500000,
    "revised_estimate": 7728261
  },
  {
    "id": "bl-caldwell-10101",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-10101",
    "original_estimate": 15000000,
    "revised_estimate": 15456522
  },
  {
    "id": "bl-caldwell-10201",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-10201",
    "original_estimate": 7500000,
    "revised_estimate": 7728261
  },
  {
    "id": "bl-caldwell-12101",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-12101",
    "original_estimate": 12500000,
    "revised_estimate": 12880435
  },
  {
    "id": "bl-caldwell-13101",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-13101",
    "original_estimate": 5000000,
    "revised_estimate": 5152174
  },
  {
    "id": "bl-caldwell-14101",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-14101",
    "original_estimate": 10000000,
    "revised_estimate": 10304348
  },
  {
    "id": "bl-caldwell-14201",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-14201",
    "original_estimate": 5000000,
    "revised_estimate": 5152174
  },
  {
    "id": "bl-caldwell-15101",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-15101",
    "original_estimate": 12500000,
    "revised_estimate": 12880435
  },
  {
    "id": "bl-caldwell-15201",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-15201",
    "original_estimate": 10000000,
    "revised_estimate": 10304348
  },
  {
    "id": "bl-caldwell-15301",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-15301",
    "original_estimate": 7500000,
    "revised_estimate": 7728261
  },
  {
    "id": "bl-caldwell-15401",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-15401",
    "original_estimate": 15000000,
    "revised_estimate": 15456522
  },
  {
    "id": "bl-caldwell-15501",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-15501",
    "original_estimate": 10000000,
    "revised_estimate": 10304348
  },
  {
    "id": "bl-caldwell-16101",
    "job_id": "j-caldwell-1",
    "cost_code_id": "cc-16101",
    "original_estimate": 7500000,
    "revised_estimate": 7728261
  }
];
