// Types barrel — re-exports AI-parse types from `./invoice` and DB row
// mirror types derived from `./database.types`.
//
// Per F1-Wave-B Plan B-1b (nwrp152 / nwrp153 umbrella Q11 D — hybrid
// schema-in-DB + types-generated + validators-in-app).
//
// CONSUMER CONTRACT
// -----------------
// Existing consumers that import from `@/lib/types/invoice` continue to
// compile unchanged — `./invoice` exports the same AI-parse symbols it
// always has (`ParsedInvoice`, `ParseResult`, etc.). NEW consumers reach
// for DB row shapes via this barrel (`@/lib/types`) or the generated
// file directly (`@/lib/types/database.types`).
//
// GENERATION
// ----------
// `database.types.ts` is regenerated by `supabase gen types typescript
// --linked` and committed alongside any migration that changes schema.
// Pre-commit hook `.claude/hooks/nightwork-type-regen.sh` blocks commits
// where migration files are staged but the regen output isn't. NEVER
// hand-edit `database.types.ts` — any edit is lost on next migration.

// AI-parse types (unchanged shape from pre-B-1b; preserved per §3.2
// sweep — 5 consumers continue to import directly from `./invoice`).
export * from "./invoice";

// Database<> generic for callers that want full schema introspection.
export type { Database } from "./database.types";

import type { Database } from "./database.types";

// Generic table-row helpers. Usage:
//   import type { Tables, InsertTables, UpdateTables } from "@/lib/types";
//   type J = Tables<"jobs">;             // Row shape
//   type Jin = InsertTables<"jobs">;     // Insert shape (optional fields)
//   type Jup = UpdateTables<"jobs">;     // Update shape (all optional)
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type InsertTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type UpdateTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];

// Named mirror types for the two B-1b–scoped entities — invoices (existing
// schema) and clients (added by B-1a migration 00100). Additional named
// mirrors land as F2-F5 adds new tenant tables; barrel pattern is the
// canonical place.
export type InvoiceRow = Tables<"invoices">;
export type InvoiceInsert = InsertTables<"invoices">;
export type InvoiceUpdate = UpdateTables<"invoices">;
export type ClientRow = Tables<"clients">;
export type ClientInsert = InsertTables<"clients">;
export type ClientUpdate = UpdateTables<"clients">;
